USE Game_Information;

--LOAD damage_type
LOAD DATA INFILE 'Data_Type.dat'
INTO TABLE Damage_Type
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

--LOAD character_race
LOAD DATA INFILE 'Character_Race.dat'
INTO TABLE Character_Race
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

--LOAD Race_Resistance
LOAD DATA INFILE 'Race_Resistance.dat'
INTO TABLE Race_Resistance
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

--LOAD Weapon
LOAD DATA INFILE 'Weapon.dat' 
INTO TABLE Weapon
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';

--LOAD Armor
LOAD DATA INFILE 'Armor.dat'
INTO TABLE Weapon
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';

--LOAD class
LOAD DATA INFILE 'Class.dat'
INTO TABLE Class
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';

--LOAD Stat
LOAD DATA INFILE 'Stat.dat'
INTO TABLE Stat
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';

--LOAD
LOAD DATA INFILE 'Class_Stat.dat'
INTO TABLE Class_Stat
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';

--LOAD Player Character
LOAD DATA INFILE 'Player_Character.dat'
INTO TABLE Player_Character
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\N';




